/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fsae_da_car_I2CSensor */

#ifndef _Included_fsae_da_car_I2CSensor
#define _Included_fsae_da_car_I2CSensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fsae_da_car_I2CSensor
 * Method:    openI2Cbus
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fsae_da_car_I2CSensor_openI2Cbus
  (JNIEnv *, jclass, jint);

/*
 * Class:     fsae_da_car_I2CSensor
 * Method:    setI2Cslave
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_fsae_da_car_I2CSensor_setI2Cslave
  (JNIEnv *, jclass, jchar);

/*
 * Class:     fsae_da_car_I2CSensor
 * Method:    writeBytes
 * Signature: ([CI)V
 */
JNIEXPORT void JNICALL Java_fsae_da_car_I2CSensor_writeBytes
  (JNIEnv *, jclass, jcharArray, jint);

/*
 * Class:     fsae_da_car_I2CSensor
 * Method:    readBytes
 * Signature: (C[CI)V
 */
JNIEXPORT void JNICALL Java_fsae_da_car_I2CSensor_readBytes
  (JNIEnv *, jclass, jchar, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
