/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeI2C */

#ifndef _Included_NativeI2C
#define _Included_NativeI2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeI2C
 * Method:    openDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeI2C_openDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeI2C
 * Method:    setSlave
 * Signature: (BI)I
 */
JNIEXPORT jint JNICALL Java_NativeI2C_setSlave
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     NativeI2C
 * Method:    writeByte
 * Signature: (BI)I
 */
JNIEXPORT jint JNICALL Java_NativeI2C_writeByte
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     NativeI2C
 * Method:    read
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_NativeI2C_read
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     NativeI2C
 * Method:    readByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_NativeI2C_readByte
  (JNIEnv *, jclass, jint);

/*
 * Class:     NativeI2C
 * Method:    writeBytes
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_NativeI2C_writeBytes
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
