/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_utdallas_utdmotorsports_car_sensors_NativeI2C */

#ifndef _Included_edu_utdallas_utdmotorsports_car_sensors_NativeI2C
#define _Included_edu_utdallas_utdmotorsports_car_sensors_NativeI2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_utdallas_utdmotorsports_car_sensors_NativeI2C
 * Method:    n_openDevice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_utdallas_utdmotorsports_car_sensors_NativeI2C_n_1openDevice
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_utdallas_utdmotorsports_car_sensors_NativeI2C
 * Method:    n_setSlave
 * Signature: (BI)I
 */
JNIEXPORT jint JNICALL Java_edu_utdallas_utdmotorsports_car_sensors_NativeI2C_n_1setSlave
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     edu_utdallas_utdmotorsports_car_sensors_NativeI2C
 * Method:    n_write
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_edu_utdallas_utdmotorsports_car_sensors_NativeI2C_n_1write
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     edu_utdallas_utdmotorsports_car_sensors_NativeI2C
 * Method:    n_writeByte
 * Signature: (BI)I
 */
JNIEXPORT jint JNICALL Java_edu_utdallas_utdmotorsports_car_sensors_NativeI2C_n_1writeByte
  (JNIEnv *, jclass, jbyte, jint);

/*
 * Class:     edu_utdallas_utdmotorsports_car_sensors_NativeI2C
 * Method:    n_read
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_edu_utdallas_utdmotorsports_car_sensors_NativeI2C_n_1read
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     edu_utdallas_utdmotorsports_car_sensors_NativeI2C
 * Method:    n_readByte
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_utdallas_utdmotorsports_car_sensors_NativeI2C_n_1readByte
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
